package model.vo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 21 15:58:23 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxsshrTapEmpFormVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxsshrTapEmpFormVOImpl() {
    }
}

