package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 01 12:54:42 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Reimbursement_VORowImpl extends ViewRowImpl {
    public static final int ENTITY_REIMBURSEMENT_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ApprovalStatus,
        BusinessUnitId,
        Comments,
        CreatedBy,
        CreationDate,
        EntitledAmount,
        ErrorMsg,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        PayrollBatchName,
        PersonId,
        ReimburesementAmount,
        ReimbursementPeriod,
        ReimbursementRequestDate,
        ReimbursementRequestId,
        ReimbursementRequestNo,
        ReimbursementType,
        SoaFlowid;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int ENTITLEDAMOUNT = AttributesEnum.EntitledAmount.index();
    public static final int ERRORMSG = AttributesEnum.ErrorMsg.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int PAYROLLBATCHNAME = AttributesEnum.PayrollBatchName.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int REIMBURESEMENTAMOUNT = AttributesEnum.ReimburesementAmount.index();
    public static final int REIMBURSEMENTPERIOD = AttributesEnum.ReimbursementPeriod.index();
    public static final int REIMBURSEMENTREQUESTDATE = AttributesEnum.ReimbursementRequestDate.index();
    public static final int REIMBURSEMENTREQUESTID = AttributesEnum.ReimbursementRequestId.index();
    public static final int REIMBURSEMENTREQUESTNO = AttributesEnum.ReimbursementRequestNo.index();
    public static final int REIMBURSEMENTTYPE = AttributesEnum.ReimbursementType.index();
    public static final int SOAFLOWID = AttributesEnum.SoaFlowid.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Reimbursement_VORowImpl() {
    }

    /**
     * Gets Reimbursement_EO entity object.
     * @return the Reimbursement_EO
     */
    public EntityImpl getReimbursement_EO() {
        return (EntityImpl) getEntity(ENTITY_REIMBURSEMENT_EO);
    }

    /**
     * Gets the attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @return the APPROVAL_STATUS
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @param value value to set the APPROVAL_STATUS
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for ENTITLED_AMOUNT using the alias name EntitledAmount.
     * @return the ENTITLED_AMOUNT
     */
    public BigDecimal getEntitledAmount() {
        return (BigDecimal) getAttributeInternal(ENTITLEDAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for ENTITLED_AMOUNT using the alias name EntitledAmount.
     * @param value value to set the ENTITLED_AMOUNT
     */
    public void setEntitledAmount(BigDecimal value) {
        setAttributeInternal(ENTITLEDAMOUNT, value);
    }

    /**
     * Gets the attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @return the ERROR_MSG
     */
    public ClobDomain getErrorMsg() {
        return (ClobDomain) getAttributeInternal(ERRORMSG);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @param value value to set the ERROR_MSG
     */
    public void setErrorMsg(ClobDomain value) {
        setAttributeInternal(ERRORMSG, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @return the PAYROLL_BATCH_NAME
     */
    public String getPayrollBatchName() {
        return (String) getAttributeInternal(PAYROLLBATCHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @param value value to set the PAYROLL_BATCH_NAME
     */
    public void setPayrollBatchName(String value) {
        setAttributeInternal(PAYROLLBATCHNAME, value);
    }

    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for REIMBURESEMENT_AMOUNT using the alias name ReimburesementAmount.
     * @return the REIMBURESEMENT_AMOUNT
     */
    public BigDecimal getReimburesementAmount() {
        return (BigDecimal) getAttributeInternal(REIMBURESEMENTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for REIMBURESEMENT_AMOUNT using the alias name ReimburesementAmount.
     * @param value value to set the REIMBURESEMENT_AMOUNT
     */
    public void setReimburesementAmount(BigDecimal value) {
        setAttributeInternal(REIMBURESEMENTAMOUNT, value);
    }

    /**
     * Gets the attribute value for REIMBURSEMENT_PERIOD using the alias name ReimbursementPeriod.
     * @return the REIMBURSEMENT_PERIOD
     */
    public String getReimbursementPeriod() {
        return (String) getAttributeInternal(REIMBURSEMENTPERIOD);
    }

    /**
     * Sets <code>value</code> as attribute value for REIMBURSEMENT_PERIOD using the alias name ReimbursementPeriod.
     * @param value value to set the REIMBURSEMENT_PERIOD
     */
    public void setReimbursementPeriod(String value) {
        setAttributeInternal(REIMBURSEMENTPERIOD, value);
    }

    /**
     * Gets the attribute value for REIMBURSEMENT_REQUEST_DATE using the alias name ReimbursementRequestDate.
     * @return the REIMBURSEMENT_REQUEST_DATE
     */
    public Timestamp getReimbursementRequestDate() {
        return (Timestamp) getAttributeInternal(REIMBURSEMENTREQUESTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REIMBURSEMENT_REQUEST_DATE using the alias name ReimbursementRequestDate.
     * @param value value to set the REIMBURSEMENT_REQUEST_DATE
     */
    public void setReimbursementRequestDate(Timestamp value) {
        setAttributeInternal(REIMBURSEMENTREQUESTDATE, value);
    }

    /**
     * Gets the attribute value for REIMBURSEMENT_REQUEST_ID using the alias name ReimbursementRequestId.
     * @return the REIMBURSEMENT_REQUEST_ID
     */
    public BigDecimal getReimbursementRequestId() {
        return (BigDecimal) getAttributeInternal(REIMBURSEMENTREQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REIMBURSEMENT_REQUEST_ID using the alias name ReimbursementRequestId.
     * @param value value to set the REIMBURSEMENT_REQUEST_ID
     */
    public void setReimbursementRequestId(BigDecimal value) {
        setAttributeInternal(REIMBURSEMENTREQUESTID, value);
    }

    /**
     * Gets the attribute value for REIMBURSEMENT_REQUEST_NO using the alias name ReimbursementRequestNo.
     * @return the REIMBURSEMENT_REQUEST_NO
     */
    public String getReimbursementRequestNo() {
        return (String) getAttributeInternal(REIMBURSEMENTREQUESTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REIMBURSEMENT_REQUEST_NO using the alias name ReimbursementRequestNo.
     * @param value value to set the REIMBURSEMENT_REQUEST_NO
     */
    public void setReimbursementRequestNo(String value) {
        setAttributeInternal(REIMBURSEMENTREQUESTNO, value);
    }

    /**
     * Gets the attribute value for REIMBURSEMENT_TYPE using the alias name ReimbursementType.
     * @return the REIMBURSEMENT_TYPE
     */
    public String getReimbursementType() {
        return (String) getAttributeInternal(REIMBURSEMENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for REIMBURSEMENT_TYPE using the alias name ReimbursementType.
     * @param value value to set the REIMBURSEMENT_TYPE
     */
    public void setReimbursementType(String value) {
        setAttributeInternal(REIMBURSEMENTTYPE, value);
    }

    /**
     * Gets the attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @return the SOA_FLOWID
     */
    public BigDecimal getSoaFlowid() {
        return (BigDecimal) getAttributeInternal(SOAFLOWID);
    }

    /**
     * Sets <code>value</code> as attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @param value value to set the SOA_FLOWID
     */
    public void setSoaFlowid(BigDecimal value) {
        setAttributeInternal(SOAFLOWID, value);
    }
}

